### ISSUE TITLE
How do you set the value?

### ISSUE THREAD

**Issue by bostondevin** [Jeevanandanj/angular-input-decimal-separator#1]
I'm trying to set a default value and it's not showing for me...

This show's up with no value: ng-model='data.values[$index]'

whereas this prints the value out fine: {{ data.values[$index] }}

**Comment by bostondevin** [comment]
Nevermind, it has to be a string. ng-model='data.values[$index].toString()' did it!

**Comment by Jeevanandanj** [comment]
Does it work? Can we close this?
