### ISSUE TITLE
Problem with negative numbers

### ISSUE THREAD

**Issue by gandaldf** [Jeevanandanj/angular-input-decimal-separator#3]
Hi! I think your directive is pretty useful.. I would like to use it in my project but it seems it can't handle negative numbers...
If you start writing a number with "-" the $viewValue and $modelValue seem to change but it doesn't appear in the input field.
Can you help me?

**Comment by gandaldf** [comment]
Here is a plunkr showing the problem:
https://plnkr.co/edit/PqJZNNsiytd8UGV6hNdF?p=preview

Here there is my solution (I've tidied up the code and I've added optional delimiters tags too):
https://plnkr.co/edit/Bf5cmBBoW8dfszRdZ9cU?p=preview

**Comment by Jeevanandanj** [comment]
Actually this is already available in the latest version. This has been already implemented and committed.
I have added plunkr for your reference.
https://plnkr.co/edit/3GrNsyx3Q0huTqEO4wrH?p=preview

Please check the commits and the home page.
https://github.com/Jeevanandanj/angular-input-decimal-separator/commit/968b14588f5fe11303b7131b260c9a53a82f157e

**Comment by gandaldf** [comment]
I've seen your https://github.com/Jeevanandanj/angular-input-decimal-separator/commit/968b14588f5fe11303b7131b260c9a53a82f157e update and your [plunkr](https://plnkr.co/edit/3GrNsyx3Q0huTqEO4wrH?p=preview) but It still having the same strange behavior: I have to press the "-" key twice to make it appear in my input field.

**Comment by Jeevanandanj** [comment]
Can you specify the browser which you have tested?

**Comment by gandaldf** [comment]
I've tested it on all my browsers:
Firefox 48.0.2
Chrome 53.0.2785.116 (64-bit)
Safari 9.1.3
Opera 36

**Comment by Jeevanandanj** [comment]
Resolved. 
Reused the if condition. 480708e642f8ab7b35554a3b8f0f7538861a49ab
