### ISSUE TITLE
Bug detecting decimal-min < 0

### ISSUE THREAD

**Issue by gandaldf** [Jeevanandanj/angular-input-decimal-separator#6]
If you try to set a negative decimal-min it can't correctly detect numbers minor than that and no error rises...

**Comment by Jeevanandanj** [comment]
Solved the issue. Please take the latest from master.
Refer the commit. 784d325b152a5ab00d9b724f86f0246284f888c1

**Comment by Jeevanandanj** [comment]
784d325b152a5ab00d9b724f86f0246284f888c1

**Comment by Jeevanandanj** [comment]
Thanks to let me know the issue.
